### ISSUE TITLE
Inverter type ID's

### ISSUE THREAD

**Issue by HAEdwin** [HectorMalot/ecur#1]
The inverter type ID's are specified (according to APSystems documentation) as follows:
Starts with 3-digit converter ID
QS1 = 802 (US and Canada)
QS1 = 801 (Europe, Middle East and Africa)
YC600-T = 407 (US and Canada)
YC600-Y = 409 (US and Canada)
YC600 = 406 or 408 (Europe, Middle East and Africa)
YC1000-3 = 503 or 504 (US and Canada)
YC1000 = 501 or 502 (Europe, Middle East and Africa)
Ends with 9-digit serialnumber
Hope this info will improve your work. Thanks for completing the protocol sheet.

**Comment by HectorMalot** [comment]
Thanks @HAEdwin, have updated this in v0.0.7
